resources: # Resource define external input and output to concourse
  - name: gitilang-repo
    type: git
    icon: github
    source:
      uri: https://github.com/BhautikChudasama/GitiLang.git
      branch: master

jobs:
  - name: build-and-publish
    public: true
    plan:
      - get: gitilang-repo
        trigger: true # Whenever any changes in master branch that performs below tasks.
      - task: build # Build our repository
        config:
          platform: linux # We are using Linux OS
          image_resource:
            type: registry-image
            source: { repository: node } # We picked NodeJS 10 version as base image
          inputs:
            - name: gitilang-repo # Pass input as our repository 
          outputs:
            - name: image # Our Builded repository
          run: # Launch BASH
            path: /bin/sh
            args:
              - -c
              - |
                echo "Node Version: $(node --version)"
                echo "NPM Version: $(npm --version)"
                cd gitilang-repo
                npm install
                npm install --global typescript@latest
                tsc
                echo "//registry.npmjs.org/:_authToken=((NPM_TOKEN))" >> .npmrc
                npm publish
        
      

                